apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonicary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonicary-demo
  template:
    metadata:
      labels:
        app: sonicary-demo
    spec:
      containers:
      - name: sonicary
        image: nokevah/sonicary:latest
        ports:
        - containerPort: 3535
          protocol: TCP
        env:
        - name: SONICARY_CONFIG_PATH
          value: /config/config.yaml
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config
        - mountPath: /app/library
          name: music
        - mountPath: /app/downloads
          name: downloads
      volumes:
      - name: config
        configMap:
          name: sonicary-demo-config
      - name: data
        hostPath:
          path: <path_to_data_folder>
          type: Directory
      - name: music
        hostPath:
          path: <path_to_music>
          type: DirectoryOrCreate
      - name: downloads
        hostPath:
          path: <path_to_download_folder>
          type: DirectoryOrCreate